### ISSUE TITLE
引入包后proxy-target-class=true 失效 

### ISSUE THREAD

**Issue by dongchenhao** [qiujiayu/autoload-cache-spring-boot-starter#1]
The bean 'redisService' could not be injected as a 'com.finup.newbrand.framework.RedisService' because it is a JDK dynamic proxy that implements:

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.

**Comment by qiujiayu** [comment]
是因为你使用了@Enableasync?

**Comment by qiujiayu** [comment]
这个问题已经解决了。用6.4.1版本。

**Comment by qiujiayu** [comment]
解决方法，在配置文件中增加下面的配置：
autoload.cache.proxy-target-class=true
