### ISSUE TITLE
AutoLoadQueueSortType在application.yml中的取值问题

### ISSUE THREAD

**Issue by rcarlosdasilva** [qiujiayu/autoload-cache-spring-boot-starter#2]
AutoLoadConfig中
`
public void setSortType(Integer sortType) {
  this.sortType=AutoLoadQueueSortType.getById(sortType);
}
`
参数为整形，STS下application.yml中会自动识别sortType的类型为枚举，如果值设置为整形，编辑器会有报错，不影响运行，但看着很扎眼。
既然已经定义了枚举，为什么不直接set一个枚举类型呢？

**Comment by qiujiayu** [comment]
这是因为之前使用spring xml配置时，注入枚举比较麻烦。
