### ISSUE TITLE
与springboot2.0.3.RELEASE整合时@Cache报错

### ISSUE THREAD

**Issue by kavin-J** [qiujiayu/autoload-cache-spring-boot-starter#4]
**jedis连接池，和lettuce连接池都会在调用@Cache时报错threw** exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.setEx([BJ[B)V] with root cause

**Comment by kavin-J** [comment]
> **jedis连接池，和lettuce连接池都会在调用@Cache时报错threw** exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.setEx([BJ[B)V] with root cause

已解决，将autoload-cache-spring-boot-starter依赖的springboot版本升级到2.0.3.RELEASE即可

**Comment by cy1ng** [comment]
改了为啥还是不是行呢
